# Generated by Django 3.1.7 on 2021-03-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_auto_20210318_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='auth_rate',
            field=models.FloatField(null=True),
        ),
    ]
